### ISSUE TITLE
Add instructions for Vite

### ISSUE THREAD

**Issue by niksy** [niksy/node-stdlib-browser#14]
```js
const stdLibBrowser = require('node-stdlib-browser');
const inject = require('@rollup/plugin-inject');

module.exports = {
  resolve: {
    alias: stdLibBrowser,
  },
  plugins: [
    {
      ...inject({
        global: [
          require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
          'global',
        ],
        process: [
          require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
          'process',
        ],
        Buffer: [
          require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
          'Buffer',
        ],
      }),
      enforce: 'post',
    },
  ],
};
```

**Comment by revick** [comment]
Tried this with Sveltekit (Vite) and couldn't get it to work - could you test in SvelteKit as well?

**Comment by niksy** [comment]
@revick do you have minimal example I could try? AFAIK, SvelteKit should use Vite under the hood.

**Comment by se1by** [comment]
I tried setting this up for a project that has a transitive dependency on `node-fetch`.
My vite.config.ts looks like this:

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import stdLibBrowser from 'node-stdlib-browser'
import inject from '@rollup/plugin-inject'

export default defineConfig({
  resolve: {
    alias: stdLibBrowser,
  },
  plugins: [
    {
      ...inject({
        process: stdLibBrowser.process,
        Buffer: [
          stdLibBrowser.buffer,
          'Buffer',
        ],
      }),
      enforce: 'post',
    },
    vue()
  ]
})
```

I got the following error:
`Uncaught SyntaxError: The requested module '/node_modules/node-stdlib-browser/node_modules/buffer/index.js' does not provide an export named 'Buffer'`

So I added `node-stdlib-browser` to the include of optimizeDeps:
```js
 optimizeDeps: {
    include: ['node-stdlib-browser']
  }
```

After that, I got this error:
`Uncaught SyntaxError: The requested module '/node_modules/process/browser.js' does not provide an export named 'default'`

Which I was unable to solve yet. Any ideas?

Thanks for your work on this project @niksy !

**Comment by niksy** [comment]
@revick @se1by can you try following configuration and see if it works for you?

```js
const inject = require('@rollup/plugin-inject');
const { defineConfig } = require('vite');

module.exports = defineConfig(async () => {
  const { default: stdLibBrowser } = await import('node-stdlib-browser');
  return {
    resolve: {
      alias: stdLibBrowser,
    },
    plugins: [
      {
        ...inject({
          global: [
            require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
            'global',
          ],
          process: [
            require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
            'process',
          ],
          Buffer: [
            require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
            'Buffer',
          ],
        }),
        enforce: 'post',
      },
    ],
  };
});
```

**Comment by sriksm19** [comment]
> @revick @se1by can you try following configuration and see if it works for you?
> 
> ```js
> const inject = require('@rollup/plugin-inject');
> 
> module.exports = async () => {
>   const { default: stdLibBrowser } = await import('node-stdlib-browser');
>   return {
>     resolve: {
>       alias: stdLibBrowser,
>     },
>     plugins: [
>       {
>         ...inject({
>           global: [
>             require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
>             'global',
>           ],
>           process: [
>             require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
>             'process',
>           ],
>           Buffer: [
>             require.resolve('node-stdlib-browser/helpers/esbuild/shim'),
>             'Buffer',
>           ],
>         }),
>         enforce: 'post',
>       },
>     ],
>   };
> };
> ```

getting the same `Uncaught SyntaxError: The requested module '/node_modules/buffer/index.js' does not provide an export named 'Buffer'` with this too

**Comment by sriksm19** [comment]
adding this seems to work:
```	
optimizeDeps: {
    include: ['buffer', 'process'],
},
```

**Comment by niksy** [comment]
@sriksm19 Hm, I’m sorry but I can’t reproduce with classic `npm init vite@latest` scaffolding. Could you please provide minimal reproducible test case? I want to see if `optimizeDeps` is really necessary.

**Comment by sriksm19** [comment]
I was getting this issue while using web3js (by ChainSafe, on latest
version). Tried your veraion first. Got the above mentioned error. Then got
it fixed after adding the opimizeDeps i posted above

**Comment by niksy** [comment]
OK, I’ve managed to *somehow* recreate it with SvelteKit, I’ve added `optimizeDeps` option and it worked, but when I removed it, it still worked 😕 

I’ve tried to remove all related cache files and forced rebuild, but still it worked without `optimizeDeps`. This is weird and makes me want to suggest adding `optimizeDeps` even though I still can’t reproduce different behavior with or without that option.

**Comment by sriksm19** [comment]
@niksy i created a sample repo for testing it out using `npm init vite@latest`, but I still had to use `optimizeDeps`.

heres the repo: https://github.com/sriksm19/vite-web3-test-for-node-stdlib-browser.git

**Comment by sriksm19** [comment]
> This worked for me, too! Thanks a lot @sriksm19 👍 On a related topic: How would a `defineConfig` ts version of this look like? I'm unsure how to replace the `require.resolve`

i am in fact using `require.resolve` within my `vite.config.ts` file for a different project. Works without any problem for me. You may try using `path.resolve` in case this fails.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1223117/152976282-4f66d1c2-f6ce-4327-82ed-c4c96518d226.png">

**Comment by niksy** [comment]
> @niksy i created a sample repo for testing it out using `npm init vite@latest`, but I still had to use `optimizeDeps`.
> 
> heres the repo: [sriksm19/vite-web3-test-for-node-stdlib-browser.git](https://github.com/sriksm19/vite-web3-test-for-node-stdlib-browser.git)

OK, will check that out and see if this happens for me!

> This worked for me, too! Thanks a lot @sriksm19 👍 On a related topic: How would a `defineConfig` ts version of this look like? I'm unsure how to replace the `require.resolve`

Maybe try this approach when using ES modules:

```js
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
```

**Comment by sriksm19** [comment]
@niksy Thank you very much for the library & vite support! 🙌 🙌

**Comment by niksy** [comment]
OK, I’ve managed to recreate it, and indeed, `optimizeDeps` fixes it. I will update documentation with examples. Thank you for your support!
