### ISSUE TITLE
How to define custom process.env.** values?

### ISSUE THREAD

**Issue by GiancarlosIO** [niksy/node-stdlib-browser#18]
Hi there!

I have implemented the library using vite but now all my values from `viteConfig.define` give me `undefined` in the browser code.

````ts
export default defineConfig({
    ... 
    define: {
      'process.env.CUSTOM_VAR': 'my_custom_var'
    },
   ...
})
````

When I use `process.env.CUSTOM_VAR` in my code it returns `undefined`

**Comment by niksy** [comment]
Are you sure this is related to this library?

**Comment by niksy** [comment]
Maybe it’s best to report this to `@rollup/plugin-inject` so we can have it properly updated?

**Comment by GiancarlosIO** [comment]
Makes sense,
I'll move this issue to vite repository since this is only related to vite.
Thanks!
