### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by milahu** [niksy/node-stdlib-browser#21]
<pre>
<span color="green">~/src/node-stdlib-browser</span> $ npm install
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> object-keys@0.2.0: Please update to the latest object-keys
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> eslint-config-niksy@10.0.2: Use eslint-config-nitpick.
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm <span>WARN</span> <span color="#9b59b6">deprecated</span> core-js@2.6.12: core-js@&lt;3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1377 packages, and audited 1378 packages in 5m

165 packages are looking for funding
  run `npm fund` for details

<span color="#c0392b">19</span> vulnerabilities (10 <span color="#fdbc4b">moderate</span>, 9 <span color="#c0392b">high</span>)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
</pre>

<pre>
<span color="green">~/src/node-stdlib-browser</span> $ ncu

Checking package.json
[====================] 70/70 100%

 buffer                     ^5.7.1  →    ^<span color="red">6.0.3</span>
 console-browserify         ^1.1.0  →    ^1.<span color="turquoise">2.0</span>
 crypto-browserify         ^3.11.0  →   ^3.<span color="turquoise">12.0</span>
 events                     ^3.0.0  →    ^3.<span color="turquoise">3.0</span>
 pkg-dir                    ^5.0.0  →    ^<span color="red">7.0.0</span>
 punycode                   ^1.4.1  →    ^<span color="red">2.1.1</span>
 readable-stream            ^3.6.0  →    ^<span color="red">4.2.0</span>
 string_decoder             ^1.0.0  →    ^1.<span color="turquoise">3.0</span>
 timers-browserify          ^2.0.4  →   ^2.0.<span color="green">12</span>
 vm-browserify              ^1.0.1  →    ^1.<span color="turquoise">1.2</span>
 @babel/cli                 ^7.2.3  →  ^7.<span color="turquoise">18.10</span>
 @babel/core                ^7.2.2  →   ^7.<span color="turquoise">19.1</span>
 @babel/preset-env         ^7.12.1  →   ^7.<span color="turquoise">19.1</span>
 @babel/register            ^7.0.0  →   ^7.<span color="turquoise">18.9</span>
 @rollup/plugin-babel       ^5.2.1  →    ^5.<span color="turquoise">3.1</span>
 @rollup/plugin-commonjs   ^20.0.0  →   ^<span color="red">22.0.2</span>
 @types/mocha               ^8.2.3  →    ^<span color="red">9.1.1</span>
 @types/node               ^16.3.0  →  ^<span color="red">18.7.21</span>
 babel-plugin-istanbul      ^6.0.0  →    ^6.<span color="turquoise">1.1</span>
 core-js                    ^2.6.5  →   ^<span color="red">3.25.3</span>
 cpy                        ^8.1.2  →    ^<span color="red">9.0.1</span>
 del                        ^6.0.0  →    ^<span color="red">7.0.0</span>
 esbuild                  ^0.14.23  →   ^0.<span color="red">15.9</span>
 eslint                    ^7.31.0  →   ^<span color="red">8.24.0</span>
 eslint-config-prettier     ^8.3.0  →    ^8.<span color="turquoise">5.0</span>
 eslint-plugin-import      ^2.23.4  →   ^2.<span color="turquoise">26.0</span>
 eslint-plugin-jsdoc       ^33.3.0  →   ^<span color="red">39.3.6</span>
 eslint-plugin-mocha        ^8.0.0  →   ^<span color="red">10.1.0</span>
 eslint-plugin-prettier     ^3.4.0  →    ^<span color="red">4.2.1</span>
 eslint-plugin-promise      ^5.1.0  →    ^<span color="red">6.0.1</span>
 eslint-plugin-unicorn     ^31.0.0  →   ^<span color="red">43.0.2</span>
 esm                       ^3.0.51  →   ^3.<span color="turquoise">2.25</span>
 execa                      ^5.1.1  →    ^<span color="red">6.1.0</span>
 husky                      ^4.3.0  →    ^<span color="red">8.0.1</span>
 lint-staged               ^10.4.2  →   ^<span color="red">13.0.3</span>
 mocha                      ^8.2.0  →   ^<span color="red">10.0.0</span>
 nodemon                    ^2.0.6  →   ^2.0.<span color="green">20</span>
 np                         ^7.6.0  →    ^7.6.<span color="green">2</span>
 parse-node-version         ^1.0.1  →    ^<span color="red">2.0.0</span>
 prettier                   ^2.4.0  →    ^2.<span color="turquoise">7.1</span>
 rollup                    ^2.32.1  →   ^2.<span color="turquoise">79.1</span>
 typescript                 ^4.3.5  →    ^4.<span color="turquoise">8.3</span>
 webpack                   ^5.65.0  →   ^5.<span color="turquoise">74.0</span>

Run <span color="turquoise">ncu -u</span> to upgrade package.json
</pre>

**Comment by theoparis** [comment]
I recommend using renovatebot to manage and update dependencies with a configuration file like this https://github.com/theoparis/typescript-template/blob/main/renovate.json.

**Comment by niksy** [comment]
Packages are explicitly left at older version for [proper browser support](https://github.com/niksy/node-stdlib-browser#browser-support).
