### ISSUE TITLE
Why doesn't net point to mock/net.js?

### ISSUE THREAD

**Issue by marijanp** [niksy/node-stdlib-browser#24]
When using the plugin with esbuild my bundled code throws the following error:
```
TypeError: Cannot read properties of null (reading 'createConnection')
```
The lines of code responsible for triggering the error are:
```
var net = require_empty();
...
ForeverAgent.prototype.createConnection = net.createConnection;
```

The README.md says that `net` has a mock implementation `mock/net.js` which makes the functions `createConnection` `noops`.
However this line sets `net` to  `mock/empty.js` i.e. null:
https://github.com/niksy/node-stdlib-browser/blob/3e7cd7f3d115ac5c4593b550e7d8c4a82a0d4ac4/index.js#L34

**Comment by niksy** [comment]
Every mock implementation should be explicitly defined in your build/bundler configuration.

**Comment by marijanp** [comment]
@niksy can you tell me how?

**Comment by niksy** [comment]
@marijanp you can try with [aliases](https://esbuild.github.io/api/#alias).
