### ISSUE TITLE
Can node-stdlib-browser resolve "Cannot read properties of null (reading 'execFile')"?

### ISSUE THREAD

**Issue by wangrongding** [niksy/node-stdlib-browser#28]
😭I am using a third-party package that calls a lot of node API and I encountered this error while building my project, can node-stdlib-browser solve this problem, please?

My project is built with vite, react, electron.

<img width="907" alt="image" src="https://github.com/niksy/node-stdlib-browser/assets/42437658/08800da4-6f2b-4b2f-9000-55687562bb01">

**Comment by niksy** [comment]
This uses `.promisify` method on some unknown `g` object which can possibly be `util`, but [`util` supports promisifying methods](https://github.com/browserify/node-util#:~:text=To%20use%20util.promisify%20and%20util.callbackify%2C%20Promises%20must%20already%20be%20available.%20If%20you%20need%20to%20support%20browsers%20like%20IE11%20that%20do%20not%20support%20Promises%2C%20use%20a%20shim.%20es6%2Dpromise%20is%20a%20popular%20one%20but%20there%20are%20many%20others%20available%20on%20npm.) so this should work, but I can’t really tell if I don’t know source code where this error happend.
