### ISSUE TITLE
Bug: `punycode` deprecation warning

### ISSUE THREAD

**Issue by philcockfield** [niksy/node-stdlib-browser#31]
runtime: `node 22`

### Summary
Running under the (soon to be LTS) `version 22` of node, a `punycode` decprecation warning is thrown when running any node script that reference the library.  Eg

```
(node:46529) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Usage (via `npm ls punycode`)

```
  └─┬ node-stdlib-browser@1.2.0
    ├── punycode@1.4.1
    └─┬ url@0.11.3
      └── punycode@1.4.1 deduped
```

**Comment by niksy** [comment]
This module already uses [userland implementation](https://github.com/mathiasbynens/punycode.js), but usage inside dependencies such as `url` should be submitted to their [issue tracker](https://github.com/defunctzombie/node-url/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by flipvh** [comment]
@niksy thnks! Seems node-url had an update specifically for this on 0.11.4. Would it help if you update this dependency? Thanks! https://github.com/defunctzombie/node-url/commit/c5e1391d8917c154b5bdeaf3b3c335513d1fd8ee

**Comment by niksy** [comment]
Sure, PR welcome!

**Comment by flipvh** [comment]
gave it a try, while not familiar at all with this project 😅, so perhaps I am doing it wrong. I get some warnings and errors when doing `npm run prerelease` and `npm run test`

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
create-require (imported by index.js)
pkg-dir (imported by index.js)
created cjs/index.js, esm/index.js in 695ms

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
path (imported by mock/process.js)
created cjs/mock/process.js, esm/mock/process.js in 523ms

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
punycode/ (imported by punycode/?commonjs-external)
qs (imported by qs?commonjs-external)
created cjs/proxy/url.js, esm/proxy/url.js in 546ms

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
querystring-es3 (imported by proxy/querystring.js)
created cjs/proxy/querystring.js, esm/proxy/querystring.js in 504ms
```

and when running `test`:

```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at node:internal/main/run_main_module:30:49

Node.js v22.6.0
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------

```

What is interesting is that the project doesnt have any fixed dependencies or package-lock? Seems a bit problematic over time or not? Thanks!

**Comment by niksy** [comment]
This has been deployed in https://github.com/niksy/node-stdlib-browser/releases/tag/v1.2.1
