### ISSUE TITLE
Don't upgrade `domain-browser` because of license change

### ISSUE THREAD

**Issue by Richienb** [niksy/node-stdlib-browser#37]
Not sure if you are aware of this already. If you were not aware of this, maybe get an OSS license checker bot.

Current version here is ok.

https://github.com/Richienb/node-polyfill-webpack-plugin/issues/55

**Comment by niksy** [comment]
Good catch!

> If you were not aware of this, maybe get an OSS license checker bot.

Any recommendations? PRs welcome!

**Comment by Richienb** [comment]
> Any recommendations?

The only one I've heard of before is [Snyk](https://snyk.io/)
